#!/bin/sh

echo "FINISH $(pwd) WITH: ${@}"

if [ ${1} -ne 0 ]
then
  # Shutdown everything and exit the process crashes or is stopped.
  s6-svscanctl -t /etc/s6
fi

# Otherwise send reload to sensu-server
s6-svc -1 /etc/s6/sensu-server
