#!/usr/bin/env bash

export PATH="/opt/sensu/embedded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export GEM_PATH="/opt/sensu/embedded/lib/ruby/gems/2.0.0"
export LANG="en_AU.utf8"

s6-svwait -U /etc/s6/sensu-server

exec s6-setuidgid sensu /opt/sensu/bin/sensu-api -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -L $LOGLEVEL
