#!/bin/sh

export PATH="/opt/sensu/embedded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/etc/sensu/plugins:/etc/sensu/handlers"
export GEM_PATH="/opt/sensu/embedded/lib/ruby/gems/2.0.0"
export LANG="en_AU.utf8"

exec s6-setuidgid sensu /opt/sensu/bin/sensu-server -c /etc/sensu/config.json -d /etc/sensu -e /etc/sensu/extensions -L $LOGLEVEL
